### ISSUE TITLE
Publish 1.5 release

### ISSUE THREAD

**Issue by garcia-jj** [garcia-jj/vraptor-plugin-hibernate4#15]

**Comment by garcia-jj** [comment]
Closed by https://github.com/garcia-jj/vraptor-plugin-hibernate4/commit/a84145351c3210856c653a4dcff041b3dc31d7f3

**Comment by dtelaroli** [comment]
One question: Why the jump between 1.0 -> 1.5?

**Comment by lucascs** [comment]
because it doesn't work with hibernate 4.0 - 4.2, only 4.3.x

**Comment by dtelaroli** [comment]
:ok_hand:
