### ISSUE TITLE
Suporte para versão 4.3.x

### ISSUE THREAD

**Issue by ericksonsilva** [garcia-jj/vraptor-plugin-hibernate4#16]
O plugin não está suportando a nova versão do Hibernate.

**Comment by garcia-jj** [comment]
Erick, obrigado pelo alerta. Ontem fiz a correção nesse pull request: https://github.com/garcia-jj/vraptor-plugin-hibernate4/pull/14

Em breve ele será disponibilizado no Maven.

**Comment by garcia-jj** [comment]
Disponibilizado no maven: http://repo1.maven.org/maven2/br/com/caelum/vraptor/vraptor-plugin-hibernate4/1.5.0/
