### ISSUE TITLE
Problema de compatibilidade com vraptor-3.5.0-snapshot

### ISSUE THREAD

**Issue by ramonPires** [garcia-jj/vraptor-plugin-hibernate4#7]
Na versão 1.0.1 do plugin  que tem como dependencia o hibernate-annotations , em conjunto com o vraptor-3.5.0-snapshot é gerado o seguinte erro: https://gist.github.com/ramonPires/e920bf8b2780c2522b32
Pelo que vi a solução é essa : http://stackoverflow.com/questions/9134436/how-can-i-resolve-java-lang-classnotfoundexception-org-hibernate-util-dtdentity , na versão 1.0.2-snapshot já foi removida a dependência do hibernate-annotations ,agora acho que é só disponibilizar essa nova versão no maven.

**Comment by garcia-jj** [comment]
Usando a release 1.0.1-SNAPHOT funciona corretamente?

**Comment by ramonPires** [comment]
Funciona , mas só depois que remove o hibernate-annotations

**Comment by garcia-jj** [comment]
Desculpe, a release 1.0.2-SNAPSHOT funciona corretamente?

**Comment by ramonPires** [comment]
não sei,ainda não testei, mas pelo que vi no pom.xml não existe mais a dependência do hibernate-annotations, eu acho que deve funcionar.

**Comment by garcia-jj** [comment]
Você pode fazer um teste? Faça um clone local do plugin, depois use o comando <code>mvn install</code> e altere seu pom.xml para usar esta versão.

**Comment by ramonPires** [comment]
eu ainda apanho do maven, é só baixar o projeto do git e chamar o mvn install dentro do diretorio do plugin?

**Comment by garcia-jj** [comment]
Exatamente. Assim ele vai instalar localmente esta versão. Depois altere o pom.xml da tua aplicação para usar esta versão. Assim a tua aplicação vai usar esta versão local.

Se os testes derem ok, o @lucascs publica o snapshot para nós :)

**Comment by ramonPires** [comment]
Um dos testes está dando erro:
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.285 sec <<< FA
ILURE!

Results :

Tests in error:
  testWithoutEnvironment(br.com.caelum.vraptor.plugin.hibernate4.PluginTest)

Tests run: 14, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:44.327s
[INFO] Finished at: Wed Apr 03 14:53:30 BRT 2013
[INFO] Final Memory: 21M/65M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
10:test (default-test) on project vraptor-plugin-hibernate4: There are test fail
ures.
[ERROR]
[ERROR] Please refer to D:\vraptor-plugin-hibernate
4\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by garcia-jj** [comment]
My bad. Fiz uma correção. Baixe a última versão e faça um novo teste.

**Comment by ramonPires** [comment]
Baixei e adicionei no meu pom.xml e tá dando esse ao ao executar o projeto: https://gist.github.com/ramonPires/002e7b01827bbb5e58bf

**Comment by garcia-jj** [comment]
Este erro é porque não há o hibernate.cfg.xml no classpath.

**Comment by ramonPires** [comment]
mas o meu hibernate.cfg.xml está no meu classpath sim.

**Comment by garcia-jj** [comment]
Se você usa o environment precisa seguir as convenções para o path do hibernate.cfg.xml. Se você não está usando o environment, precisa ver se ele está sendo copiado corretamente para o output.

Fiz alguns testes aqui e tudo rodou perfeitamente. Quando apaguei o hibernate.cfg.xml recebi exatamente o mesmo erro teu. Vou já alterar o fonte para ele lançar uma exception melhor.

Se preferir posso compartilhar meu projeto de exemplo (que não usa mavem).

**Comment by garcia-jj** [comment]
Closed by 6211844855a7011412539a0945e925c1d51ebff1.
