### ISSUE TITLE
Publicar no repositório do maven

### ISSUE THREAD

**Issue by dennysfredericci** [garcia-jj/vraptor-plugin-hibernate4#9]
Não encontrei a ultima versão deste plugin no repositório do maven, a versão que possui a integração com o vraptor environment.

**Comment by lucascs** [comment]
Tá sim:

http://repo1.maven.org/maven2/br/com/caelum/vraptor/vraptor-plugin-hibernate4/

**Comment by dennysfredericci** [comment]
Sorry! My fault!

**Comment by lucascs** [comment]
No problem =)
